### ISSUE TITLE
Roadmap to package

### ISSUE THREAD

**Issue by hxjo** [hxjo/fastapi-inertia#4]
- [x] Handle external redirects (through 409 with different location)
- [x] Useful "back" method which redirects to referrer
- [x] Form
  - [x] 422 exceptions custom handler
  - [x] errorBags
- [x] reorganize project structure
- [x] Add more examples
- [x] Clearer documentation 
- [x] Add docstring to all functions and methods
- [x] github workflow for tests
- [x] introduce changelog
- [x] add licence
- [x] improve README
- [x] ssr documentation 
- [x] check & improve python compatibility 
- [x] publish
